export const LOAD_COUNTIES='LOAD_COUNTIES';
export const SELECT_COUNTY='SELECT_COUNTY';
export const LOAD_CITIES='LOAD_CITIES';
export const SELECT_CITY='SELECT_CITY';
export const DELETE_CITY='DELETE_CITY';
export const MODIFY_CITY='MODIFY_CITY';
export const NEW_CITY='NEW_CITY';